import { create } from 'zustand'
import * as repo from '../data/index.js'
import { useAuthStore } from './useAuthStore.js'
import { runRollover } from '../data/rollover.js'
import { regenerateFutureInstances } from '../data/recurrence.js'
import { todayStr, addDaysStr, timeStrToMinutes } from '../utils/dateUtils.js'

// True once an occurrence is entirely in the past: an earlier date, or today
// with its end time (start + duration) already behind the clock. All-day
// items (no time) only count once their date has passed.
export function hasElapsed(date, time, durationMinutes = 0) {
  const today = todayStr()
  if (date < today) return true
  if (date > today || !time) return false
  const now = new Date()
  return timeStrToMinutes(time) + (durationMinutes || 0) <= now.getHours() * 60 + now.getMinutes()
}

const SLEEP_CATEGORY_NAME = 'Sleep'
const SLEEP_CATEGORY_COLOR = '#8a5fd6'
const SLEEP_ITEM_TITLE = 'Sleep'

// A ghost/worked_on finalize returns a non-recurring item to the backlog
// (isUnscheduled: true). If the user then acts directly on one of its
// instances again (move it, tick its percent, edit its notes), that
// instance is definitely still scheduled — so the item's stale backlog flag
// needs correcting, otherwise the item sits in the backlog while its own
// instance is simultaneously live on the calendar.
async function clearUnscheduledFlag(itemId) {
  const item = await repo.getItem(itemId)
  if (item?.isUnscheduled) {
    await repo.saveItem({ id: itemId, isUnscheduled: false })
  }
}

export const useEntityStore = create((set, get) => ({
  categories: [],
  items: [],
  instancesByDate: {}, // date -> ScheduledInstance[]
  allInstances: [], // every instance, regardless of date — backs "has a future/past instance" checks
  journalsByDate: {}, // date -> DayJournal|null
  allJournals: [], // every journal entry — backs the Stats page's screen-time aggregates
  initialized: false,

  init: async () => {
    if (get().initialized) return
    await runRollover(todayStr())
    await Promise.all([
      get().refreshCategories(),
      get().refreshItems(),
      get().refreshAllInstances(),
      get().refreshAllJournals(),
    ])
    set({ initialized: true })
  },

  refreshCategories: async () => {
    const categories = await repo.getAllCategories()
    set({ categories })
  },

  refreshItems: async () => {
    const items = await repo.getAllItems()
    set({ items })
  },

  refreshAllInstances: async () => {
    const allInstances = await repo.getAllInstances()
    set({ allInstances })
  },

  refreshAllJournals: async () => {
    const allJournals = await repo.getAllJournals()
    set({ allJournals })
  },

  loadInstancesForDate: async (date) => {
    await runRollover(todayStr())
    const instances = await repo.getInstancesForDate(date)
    set((s) => ({ instancesByDate: { ...s.instancesByDate, [date]: instances } }))
    await get().refreshAllInstances()
    return instances
  },

  loadJournalForDate: async (date) => {
    const journal = await repo.getJournalForDate(date)
    set((s) => ({
      journalsByDate: { ...s.journalsByDate, [date]: journal },
      allJournals: journal
        ? [...s.allJournals.filter((j) => j.date !== date), journal]
        : s.allJournals,
    }))
    return journal
  },

  // ---- Items -------------------------------------------------------------

  createItem: async (itemPartial) => {
    // Sync is only meaningful when someone's signed in — an item created
    // while signed out defaults to local-only (syncEnabled: false) so it
    // stays put and never gets pushed to the cloud, even after a later
    // sign-in. Signed in, new items still default to syncing. An explicit
    // syncEnabled in itemPartial (the item modal's toggle) always wins.
    const syncDefault = { syncEnabled: Boolean(useAuthStore.getState().user) }
    // New items land at the TOP of the backlog. saveItem's default order is
    // Date.now() (a large positive), which sorts last; a negative order
    // beats every positive/renumbered one, and the monotonic clock keeps
    // successive creations in newest-first order. An explicit order in
    // itemPartial still wins.
    const saved = await repo.saveItem({ order: -Date.now(), ...syncDefault, ...itemPartial })
    // A recurring item's instances are normally (re)generated by updateItem
    // when it detects the recurrence rule changed — but a brand new item is
    // often created with its recurrence already set in this same save, so
    // there's no "before" state for updateItem to diff against. Generate
    // instances here too, up front, so a recurring item shows up right away.
    if (saved.recurrence) {
      await regenerateFutureInstances(saved, todayStr())
    }
    await get().refreshItems()
    await get().reloadLoadedDates()
    await get().refreshAllInstances()
    return saved
  },

  updateItem: async (itemId, patch) => {
    const before = get().items.find((i) => i.id === itemId) ?? (await repo.getItem(itemId))
    const saved = await repo.saveItem({ id: itemId, ...patch })

    // Regenerating deletes and recreates every future instance (fresh ids,
    // percent reset to 0, time reset to the series' regular time) — only
    // actually needed when the recurrence RULE changed, since that's what
    // determines which dates get an instance at all. A duration/all-day-only
    // change doesn't affect which dates recur, so it's patched onto each
    // existing instance in place instead: regenerating for a duration change
    // used to blow away an in-flight edit to one specific occurrence (e.g.
    // moving its time, changed right before this call in the item modal),
    // snapping it back to the template's default time.
    // Compare actual values, not key presence — the item modal always sends
    // the full form (title, durationMinutes, isAllDay, recurrence, ...) on
    // every save, so `'durationMinutes' in patch` is always true whether or
    // not it actually changed.
    const recurrenceChanged =
      JSON.stringify(before?.recurrence ?? null) !== JSON.stringify(saved.recurrence ?? null)
    const durationOrAllDayChanged =
      before && (before.durationMinutes !== saved.durationMinutes || before.isAllDay !== saved.isAllDay)

    if (saved.recurrence && recurrenceChanged) {
      await regenerateFutureInstances(saved, todayStr())
    } else if (before?.recurrence && recurrenceChanged && !saved.recurrence) {
      // recurrence was just turned off — clear the remaining future instances of the old series
      const instances = await repo.getInstancesForItem(itemId)
      for (const inst of instances.filter((i) => !i.finalized)) {
        await repo.deleteInstance(inst.id)
      }
    } else if (durationOrAllDayChanged) {
      const instances = await repo.getInstancesForItem(itemId)
      for (const inst of instances.filter((i) => !i.finalized)) {
        await repo.saveInstance({
          ...inst,
          durationMinutes: saved.durationMinutes,
          isAllDay: saved.isAllDay,
          time: saved.isAllDay ? null : inst.time,
        })
      }
    }
    await get().refreshItems()
    await get().reloadLoadedDates()
    await get().refreshAllInstances()
    return saved
  },

  deleteItem: async (itemId) => {
    await repo.deleteItem(itemId)
    await get().refreshItems()
    await get().reloadLoadedDates()
    await get().refreshAllInstances()
  },

  // "Delete series" for a recurring item — stops the series from a given
  // point forward without touching history. `fromDate` is the occurrence the
  // user deleted from (defaults to today): that occurrence and every later
  // one are removed, every earlier one is left alone.
  //  - Nothing left at all  -> delete the item (repo keeps it archived if any
  //    of its instances were finalized history).
  //  - Occurrences remain before the cutoff -> cap the rule with an endDate
  //    so the series legitimately ends there.
  //  - Cutoff at/before the series start -> clear the rule.
  // Either way habit tracking is turned off — a deleted series shouldn't keep
  // showing on the Stats page.
  deleteFutureSeries: async (itemId, fromDate) => {
    const cutoff = fromDate ?? todayStr()
    const item = await repo.getItem(itemId)
    const instances = await repo.getInstancesForItem(itemId)
    for (const inst of instances) {
      if (inst.date >= cutoff) {
        await repo.deleteInstance(inst.id)
      }
    }
    const remaining = instances.filter((inst) => inst.date < cutoff)
    const rule = item?.recurrence

    if (remaining.length === 0) {
      await repo.deleteItem(itemId)
    } else if (rule && rule.startDate < cutoff) {
      const newEnd = addDaysStr(cutoff, -1)
      const endDate = rule.endDate && rule.endDate < newEnd ? rule.endDate : newEnd
      await repo.saveItem({ id: itemId, recurrence: { ...rule, endDate }, isHabit: false })
    } else {
      await repo.saveItem({ id: itemId, recurrence: null, isHabit: false })
    }
    await get().refreshItems()
    await get().reloadLoadedDates()
    await get().refreshAllInstances()
  },

  adjustDuration: async (itemId, deltaMinutes) => {
    const item = get().items.find((i) => i.id === itemId) ?? (await repo.getItem(itemId))
    const current = item.durationMinutes ?? 0
    const next = Math.max(10, current + deltaMinutes)
    return get().updateItem(itemId, { durationMinutes: next })
  },

  // Item-level percent — the "resting" value for a backlog (unscheduled)
  // item. Once an item is scheduled, its progress lives on the instance
  // instead (see setInstancePercentComplete) since a recurring series needs
  // each occurrence tracked independently.
  setPercentComplete: async (itemId, percent) => {
    const clamped = Math.max(0, Math.min(100, Math.round(percent)))
    return get().updateItem(itemId, { percentComplete: clamped })
  },

  setInstancePercentComplete: async (instanceId, percent) => {
    const clamped = Math.max(0, Math.min(100, Math.round(percent)))
    const inst = await repo.getInstance(instanceId)
    const patch = { percentComplete: clamped }

    // Remember where it stood before being completed so "Mark incomplete" can
    // put it back; forget it once it's no longer complete.
    if (clamped >= 100 && inst.percentComplete < 100) patch.percentBeforeComplete = inst.percentComplete
    else if (clamped < 100) patch.percentBeforeComplete = null

    // A finalized instance's status is normally locked-in history — but the
    // user can still go back and correct a past day (e.g. mark a ghost
    // complete because it actually got done), so recompute it here rather
    // than leaving it stuck at whatever it was originally finalized as.
    if (inst.finalized) {
      if (clamped >= 100) patch.status = 'completed'
      else if (clamped > inst.startPercent) patch.status = 'worked_on'
      else patch.status = 'ghost'
      patch.finalPercent = clamped
    }

    const updated = await repo.saveInstance({ ...inst, ...patch })
    await clearUnscheduledFlag(inst.itemId)
    await get().loadInstancesForDate(inst.date)

    // Keep a non-recurring item's own percent in sync too, so the backlog
    // (where it's likely sitting after ghosting) reflects the correction.
    if (clamped === 100 && inst.finalized) {
      const item = await repo.getItem(inst.itemId)
      if (item && !item.recurrence) {
        await repo.saveItem({ id: item.id, percentComplete: clamped })
      }
    }
    await get().refreshItems()
    return updated
  },

  markInstanceComplete: async (instanceId) => {
    return get().setInstancePercentComplete(instanceId, 100)
  },

  // Notes live on the instance once an item is scheduled, same reasoning as
  // percent: a recurring series' occurrences need their own notes, not one
  // shared value that edits every occurrence at once.
  setInstanceNotes: async (instanceId, notes) => {
    const inst = await repo.getInstance(instanceId)
    const updated = await repo.saveInstance({ ...inst, notes })
    await clearUnscheduledFlag(inst.itemId)
    await get().loadInstancesForDate(inst.date)
    await get().refreshItems()
    return updated
  },

  // Changes just this one occurrence's duration/all-day, leaving the series'
  // template and every other occurrence untouched — the counterpart to
  // updateItem's duration handling, which is for "apply to every future
  // occurrence" instead (see the item modal's "Save for all" option).
  setInstanceDuration: async (instanceId, durationMinutes, isAllDay) => {
    const inst = await repo.getInstance(instanceId)
    const updated = await repo.saveInstance({
      ...inst,
      durationMinutes,
      isAllDay,
      time: isAllDay ? null : inst.time,
    })
    await get().loadInstancesForDate(inst.date)
    await get().refreshAllInstances()
    return updated
  },

  // ---- Scheduling ----------------------------------------------------------

  // Dragging an item onto a new date reschedules it — its existing
  // not-yet-finalized (today/future) instance(s) are removed so it moves
  // rather than duplicates. A finalized (past) instance is history and is
  // left untouched; recurring series are left untouched too (dropping a
  // recurring item just adds a one-off extra instance alongside its series).
  scheduleItemOnDate: async (itemId, date, opts = {}) => {
    const item = await repo.getItem(itemId)
    const isAllDay = opts.isAllDay ?? item.isAllDay
    // Scheduling straight onto a day that's already passed means the event
    // can't still be pending — there's no "later today" left for it to
    // happen in. Marking it complete up front (rather than waiting for the
    // next rollover pass) makes getDisplayStatus show it as done right away;
    // rollover still finalizes it into locked-in history the normal way.
    const time = isAllDay ? null : (opts.time ?? '12:00')
    const isPastDate = hasElapsed(date, time, item.durationMinutes)

    if (!item.recurrence) {
      const existing = await repo.getInstancesForItem(itemId)
      for (const inst of existing.filter((i) => !i.finalized)) {
        await repo.deleteInstance(inst.id)
      }
    }

    const instance = await repo.saveInstance({
      itemId,
      date,
      time,
      durationMinutes: item.durationMinutes,
      isAllDay,
      notes: item.notes,
      percentComplete: isPastDate ? 100 : item.percentComplete,
    })
    await repo.saveItem({ id: itemId, isUnscheduled: false })
    await get().refreshItems()
    await get().reloadLoadedDates()
    await get().loadInstancesForDate(date)
    return instance
  },

  moveInstanceTime: async (instanceId, newTime) => {
    const inst = await repo.getInstance(instanceId)
    const elapsed = hasElapsed(inst.date, newTime, inst.durationMinutes)
    const updated = await repo.saveInstance({
      ...inst,
      time: newTime,
      isAllDay: false,
      percentComplete: elapsed ? 100 : inst.percentComplete,
    })
    await clearUnscheduledFlag(inst.itemId)
    await get().loadInstancesForDate(inst.date)
    await get().refreshItems()
    return updated
  },

  // Moving a task to a different day (from the item modal) restarts its
  // tracking for that day — otherwise a stale locked-in status from wherever
  // it used to be finalized could carry over to the new date.
  moveInstanceDate: async (instanceId, newDate) => {
    const inst = await repo.getInstance(instanceId)
    if (newDate === inst.date) return inst
    const updated = await repo.saveInstance({
      ...inst,
      date: newDate,
      // Only a previously-finalized (locked-in-history) instance needs its
      // percent reset — otherwise it shows up already "completed" on the new
      // date before any work has happened there. A still-pending instance
      // just being rescheduled keeps whatever in-progress percent it had.
      percentComplete: hasElapsed(newDate, inst.isAllDay ? null : inst.time, inst.durationMinutes)
        ? 100
        : inst.finalized ? 0 : inst.percentComplete,
      finalized: false,
      status: 'pending',
      startPercent: null,
      finalPercent: null,
    })
    await clearUnscheduledFlag(inst.itemId)
    await get().reloadLoadedDates()
    await get().loadInstancesForDate(newDate)
    await get().refreshItems()
    return updated
  },

  unscheduleInstance: async (instanceId) => {
    const inst = await repo.getInstance(instanceId)
    await repo.deleteInstance(instanceId)
    // A just-unscheduled item jumps to the top of the backlog — a negative
    // order beats every Date.now()/renumbered positive one, and the
    // monotonic clock keeps successive unschedules in newest-first order.
    await repo.saveItem({ id: inst.itemId, isUnscheduled: true, order: -Date.now() })
    await get().refreshItems()
    await get().loadInstancesForDate(inst.date)
  },

  // Removes just this one occurrence of a recurring series — the item and
  // its other instances are untouched. Distinct from unscheduleInstance,
  // which is for a non-recurring item and puts it back in the backlog;
  // a recurring series has no single "the item" state to return to.
  deleteInstanceOnly: async (instanceId) => {
    const inst = await repo.getInstance(instanceId)
    await repo.deleteInstance(instanceId)
    await get().loadInstancesForDate(inst.date)
    await get().refreshAllInstances()
  },

  reloadLoadedDates: async () => {
    const dates = Object.keys(get().instancesByDate)
    await Promise.all(dates.map((d) => get().loadInstancesForDate(d)))
  },

  // ---- Parent/child links (informational only) ----------------------------

  linkParentChild: async (parentId, childId) => {
    if (parentId === childId) return
    const parent = await repo.getItem(parentId)
    const child = await repo.getItem(childId)
    if (!parent.childIds.includes(childId)) {
      await repo.saveItem({ id: parentId, childIds: [...parent.childIds, childId] })
    }
    if (!child.parentIds.includes(parentId)) {
      await repo.saveItem({ id: childId, parentIds: [...child.parentIds, parentId] })
    }
    await get().refreshItems()
  },

  unlinkParentChild: async (parentId, childId) => {
    const parent = await repo.getItem(parentId)
    const child = await repo.getItem(childId)
    await repo.saveItem({ id: parentId, childIds: parent.childIds.filter((x) => x !== childId) })
    await repo.saveItem({ id: childId, parentIds: child.parentIds.filter((x) => x !== parentId) })
    await get().refreshItems()
  },

  // ---- Backlog ordering ----------------------------------------------------

  /**
   * Moves draggedId to sit just before/after targetId in the shared backlog
   * order, then renumbers everyone sequentially. Renumbering the whole list
   * (rather than fractional-indexing between neighbors) is simplest and
   * plenty cheap for a personal list of this size.
   *
   * If draggedId has subtasks, they move with it as a contiguous block
   * (in their existing relative order) so reordering a parent can't strand
   * its children elsewhere in the list.
   */
  reorderItem: async (draggedId, targetId, position) => {
    if (draggedId === targetId) return
    const ordered = get().items.slice().sort((a, b) => (a.order ?? 0) - (b.order ?? 0))
    const dragged = ordered.find((i) => i.id === draggedId)
    if (!dragged) return
    const childIds = new Set(dragged.childIds)
    const draggedGroup = [dragged, ...ordered.filter((i) => childIds.has(i.id))]
    const rest = ordered.filter((i) => i.id !== draggedId && !childIds.has(i.id))
    const targetIndex = rest.findIndex((i) => i.id === targetId)
    if (targetIndex === -1) return
    const insertIndex = position === 'after' ? targetIndex + 1 : targetIndex
    rest.splice(insertIndex, 0, ...draggedGroup)

    // Show the new order immediately, before the (sequential) IndexedDB
    // writes finish — otherwise the list sits in its old order for a moment
    // after the drop and then visibly jumps once the store refreshes.
    const newOrder = new Map(rest.map((item, idx) => [item.id, idx]))
    set((s) => ({
      items: s.items.map((i) => (newOrder.has(i.id) ? { ...i, order: newOrder.get(i.id) } : i)),
    }))

    for (let i = 0; i < rest.length; i++) {
      if (rest[i].order !== i) {
        await repo.saveItem({ id: rest[i].id, order: i })
      }
    }
    await get().refreshItems()
  },

  // ---- Categories ------------------------------------------------------

  saveCategory: async (categoryPartial) => {
    const saved = await repo.saveCategory(categoryPartial)
    await get().refreshCategories()
    return saved
  },

  deleteCategory: async (categoryId) => {
    await repo.deleteCategory(categoryId)
    await get().refreshCategories()
    await get().refreshItems()
  },

  // ---- Sleep -------------------------------------------------------------

  /**
   * Sets tonight's sleep as a normal scheduled item (bedtime + computed
   * duration) so it renders on the day grid like anything else — including
   * running past midnight via the overnight-continuation rendering. Reuses
   * a single "Sleep" item/category across calls rather than creating a new
   * one each time.
   * @param {{date: string, bedtime: string, wakeTime: string, recurring: boolean}} args
   */
  setSleepSchedule: async ({ date, bedtime, wakeTime, recurring }) => {
    const bedMinutes = timeStrToMinutes(bedtime)
    const wakeMinutes = timeStrToMinutes(wakeTime)
    const durationMinutes =
      wakeMinutes <= bedMinutes ? 1440 - bedMinutes + wakeMinutes : wakeMinutes - bedMinutes

    let sleepCategory = get().categories.find((c) => c.name === SLEEP_CATEGORY_NAME)
    if (!sleepCategory) {
      sleepCategory = await repo.saveCategory({ name: SLEEP_CATEGORY_NAME, color: SLEEP_CATEGORY_COLOR })
      await get().refreshCategories()
    }

    let sleepItem = get().items.find((i) => i.title === SLEEP_ITEM_TITLE)
    if (!sleepItem) {
      sleepItem = await repo.saveItem({
        title: SLEEP_ITEM_TITLE,
        categoryId: sleepCategory.id,
        durationMinutes,
        isUnscheduled: true,
      })
      await get().refreshItems()
    }

    if (recurring) {
      await get().updateItem(sleepItem.id, {
        durationMinutes,
        categoryId: sleepCategory.id,
        recurrence: {
          freq: 'daily',
          interval: 1,
          byWeekday: null,
          startDate: date,
          endDate: null,
          time: bedtime,
        },
        isUnscheduled: false,
      })
    } else {
      await get().updateItem(sleepItem.id, { durationMinutes, categoryId: sleepCategory.id, recurrence: null })
      await get().scheduleItemOnDate(sleepItem.id, date, { time: bedtime })
    }
  },

  // ---- Journal -----------------------------------------------------------

  saveJournalForDate: async (date, patch) => {
    const journal = await repo.saveJournal({ date, ...patch })
    set((s) => ({
      journalsByDate: { ...s.journalsByDate, [date]: journal },
      allJournals: [...s.allJournals.filter((j) => j.date !== date), journal],
    }))
    return journal
  },

  // ---- Search --------------------------------------------------------------

  search: async (query) => repo.searchItems(query),
}))
